spring:
  application:
    name: postgres-testcontainer
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/dibyajyoti
    username: postgres
    password: postgres
    properties:
      schema: project

---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:tc:postgresql:///testdb?TC_IMAGE_TAG=14-alpine
---
